sudo: false
language: csharp
env:
    global:
       - "BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
       - "BUILD_DIR=$TRAVIS_BUILD_DIR"
script:
    - ./build_main.sh
    - ./build_engine.sh
    - ./build_editor.sh
    - ./build_speedrun.sh
    - ./build_fixmonolive.sh
after_success:
    - wget http://fezmod.xyz/files/travis/deploy.sh
    - chmod +x ./deploy.sh
    - ./deploy.sh
    - rm ./deploy.sh
